Update side-post.php
Exception: Avoid confusing by telling the user that the post type $ptype is not found instead of just telling that $ptype is not found.